### PR TITLE
[wip] fix deploy action

### PR DESCRIPTION
**Pull request by mrparkers**

### CODE REVIEW

**Comment by mrparkers** [comment]
Sorry!  I did not mean to open this PR against this repo.

**Comment by adamhathcock** [comment]
No problem but it makes me think if I have reference cycle issues 🤔

**Comment by mrparkers** [comment]
I installed the `NewtonsoftJson` package because of some JSON cycling issues when attempting to use this backend with the react-redux front-end.  I'm no expert on .net core though so there may be better ways to fix this.

If you want, I can open a PR with that first commit you see in the changelog.

**Comment by adamhathcock** [comment]
It’s a common problem with the new System.Text.Json that should be fixed with .NET 5.

Happy to accept a PR but just didn’t think the model was complex enough for it.

**Pull request closed without merging**
