### PR TITLE
Code cleanup.

### PR DESCRIPTION
**Pull request by 1fisedi**

### CODE REVIEW

**Comment by adamhathcock** [comment]
Why do this?  What tool did you run this through?

**Comment by 1fisedi** [comment]
@adamhathcock , to improve code readability and follow some common conventions, from vs tools and to continue to work on suggested issues, later on.

**Comment by adamhathcock** [comment]
What conventions?  What tooling specifically?  There are a lot.

I'm not against formatting changes but it needs to be more considered.  I'd rather have real functional changes from PRs then we can discuss standards where needed.

**Comment by 1fisedi** [comment]
Simply using integrated standard Visual Studio code cleanup tools, and framework design guidelines. Next, I was planning on using Codacy to improve code quality, Though, if the functionality is the only priority, I could try focusing on that.

**Comment by adamhathcock** [comment]
Sorry.  I don't believe running the code through automated tools without thought and some agreement on what's applicable is useful.

Functionality and examples of structure is the purpose of this project.  A .NET Core 3 update would be an example of a useful update.

**Pull request closed without merging**
