### PR TITLE
Add fe

### PR DESCRIPTION
**Pull request by nerem**

### CODE REVIEW

**Comment by adamhathcock** [comment]
This looked great, why delete?

**Comment by nerem** [comment]
I'm sorry, i wanted to create this PR on my fork, not here. Unfortunately, by default, github always tries to create PR against the original repo instead of using the fork.

We are creating a workshop and used the backend here as a base. We are adding a frontend based on https://github.com/angelguzmaning/ts-redux-react-realworld-example-app. Some fixes are needed and it's still work in progress. If you are interested, I could open such a PR again, when I'm finished adding the frontend.

If you are only interested in version upgrades of dependencies, i could create such a PR as well.

**Comment by adamhathcock** [comment]
Any and all updates I would accept here.  Looks like you had done a lot. 

If anything was still broken for this project and you needed, I could fix it myself.  The jumpstart would help a lot.

**Comment by nerem** [comment]
still wondering if you really want a frontend which is basically a copy of the repo i sent above or if you'd prefer having the dependencies updates as well as some small api fixes :-)

**Comment by adamhathcock** [comment]
any relevant changes to this repo are good changes.

**Pull request closed without merging**
