### PR TITLE
.NET 5

### PR DESCRIPTION
**Pull request by MoienTajik**
- [x] Update project to .NET 5
- [x] Upgrade NuGet packages to the latest version
- [x] Use C# 9 top-level statements in `Program.cs`
- [x] Add proper `CancellationToken` support to the project, see #41 
- [x] Replace simple `POCO` classes with C# 9 `Records`
- [x] Use `Task Eliding` instead of `async/await` wherever possible

### CODE REVIEW

**Comment by adamhathcock** [comment]
Thanks.  I haven't even installed .NET 5 yet!

**Comment by MoienTajik** [comment]
So this could be a good starting point! 😄

**Comment by adamhathcock** [comment]
Undraft when you're done and I'll merge

**Comment by MoienTajik** [comment]
Done, It's ready for review.

**Pull request merged**
